### ISSUE TITLE
Prepare code template for training

### ISSUE THREAD

**Issue by addianto** [addianto/sikomo-js-backend#2]
## Tasks

The tasks sorted by priority:

- [ ] Prepare at least 20 methods to be implemented by participants
- [ ] Refactor data model to use class-like data model, e.g., https://github.com/gtsopour/nodejs-shopping-cart/blob/master/models/cart.js
- [ ] Set up test reporting and coverage analysis on SonarCloud
- [ ] Prepare README.md
- [ ] Refactor code architecture to look more fluent and match closely with the best practices of using Express (and ESM module standard)
